"use client";

import type { Route } from "next";
import { Bookmark, Home, Search, User } from "lucide-react";

import { BottomNav, type BottomNavItem } from "./BottomNav";

const ITEMS: BottomNavItem[] = [
  { href: "/", label: "Home", icon: Home, match: "exact" },
  { href: "/search", label: "Search", icon: Search, match: "prefix" },
  // app/saved/page.tsx exists; the cast covers the typed-routes manifest
  // until it is regenerated by the next `next dev`/`next build`.
  { href: "/saved" as Route, label: "Saved", icon: Bookmark, match: "prefix" },
  { href: "/profile", label: "Profile", icon: User, match: "prefix" }
];

export function AppBottomNav() {
  return <BottomNav items={ITEMS} />;
}
